# Generated by Django 3.2.7 on 2021-10-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='Valeriu Alaci', max_length=50),
            preserve_default=False,
        ),
    ]
