# Generated by Django 3.2.7 on 2021-10-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture4',
            field=models.ImageField(upload_to=''),
        ),
    ]
